[
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.AlreadyExistingItemException",
    "id": 1,
    "reason": "You tried to create an object which already exist in our repository",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.BridgeLifecycleException",
    "id": 2,
    "reason": "You tried a life cycle transition which is not allowed",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ExternalUserException",
    "id": 3,
    "reason": "We were unable to process your request. Please contact Red Hat support if the error persists.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ItemNotFoundException",
    "id": 4,
    "reason": "You tried to create an object which already exist in our repository",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.CloudEventSerializationException",
    "id": 5,
    "reason": "You try to serialize a cloud event and something goes wrong, check if format follows specification",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.CloudEventDeserializationException",
    "id": 6,
    "reason": "You try to deserialize a cloud event and something goes wrong, check if format follows specification",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.GatewayProviderException",
    "id": 7,
    "reason": "Something failed related with gateway execution or resolution",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.BadRequestException",
    "id": 8,
    "reason": "The request is not valid.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.InternalPlatformException",
    "id": 9,
    "reason": "There was an internal exception. This is supposed not to be fixable by the user, so you should open a bug with all the information you have.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.PrometheusNotInstalledException",
    "id": 10,
    "reason": "Prometheus is not installed on the shard.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.ConnectorCreationException",
    "id": 11,
    "reason": "Error while creating the connector on MC Fleet Manager.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.OidcTokensNotInitializedException",
    "id": 12,
    "reason": "Oidc Tokens have not been initialized.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.HTTPResponseException",
    "id": 13,
    "reason": "The HTTP response status code was not 2xx.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.VaultException",
    "id": 14,
    "reason": "An error occurred fetching the secrets from the vault.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.TechnicalBearerTokenNotConfiguredException",
    "id": 15,
    "reason": "Technical bearer token was not configured.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ForbiddenRequestException",
    "id": 16,
    "reason": "The user is not authorized to access the resource",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.ConnectorDeletionException",
    "id": 17,
    "reason": "Error while deleting the connector on MC Fleet Manager",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.ConnectorGetException",
    "id": 18,
    "reason": "Error while retrieving the connector on MC Fleet Manager",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorLifecycleException",
    "id": 19,
    "reason": "You tried a life cycle transition which is not allowed",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.DeserializationException",
    "id": 20,
    "reason": "Error during the deserialization of a resource.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.UnclassifiedConstraintViolationException",
    "id": 21,
    "reason": "A ConstraintViolation has not been mapped to an ExternalUserException. The raw violation is shown.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorTemplateDefinitionException",
    "id": 22,
    "reason": "The Transformation Template for the Processor is invalid",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorMissingGatewayException",
    "id": 23,
    "reason": "The Processor is missing a Gateway definition.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorGatewayParametersMissingException",
    "id": 24,
    "reason": "The Processor Gateway definition is missing parameters.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorGatewayNotRecognisedException",
    "id": 25,
    "reason": "The Processor Gateway type is not recognised.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorGatewayParametersNotValidException",
    "id": 26,
    "reason": "One or more of the Processor Gateway parameters are invalid.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorGatewayUnclassifiedException",
    "id": 27,
    "reason": "One or more of the Processor Gateway parameters are invalid.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.UnsupportedErrorHandlerGatewayException",
    "id": 30,
    "reason": "The specified ErrorHandler Action is unsupported.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.ProcessorFilterDefinitionException",
    "id": 32,
    "reason": "Unable to deserialize Filter definition.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.InvalidCloudProviderException",
    "id": 33,
    "reason": "The selected Cloud Provider is not valid.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.InvalidRegionException",
    "id": 34,
    "reason": "The selected Region is not valid.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.InvalidURLException",
    "id": 35,
    "reason": "Shard Operator received an invalid URL for the BridgeIngress endpoint.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.ProvisioningTimeOutException",
    "id": 36,
    "reason": "Your request was not complete within the configured time-out.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.ProvisioningMaxRetriesExceededException",
    "id": 37,
    "reason": "Your request failed after the maximum number of configured re-try attempts.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.ProvisioningReplicaFailureException",
    "id": 38,
    "reason": "A ReplicaSet failed to be provisioned for your request.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.ManagedConnectorException",
    "id": 39,
    "reason": "A Managed Connector failed to be provisioned for your request.",
    "type": "PLATFORM"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.NoQuotaAvailable",
    "id": 40,
    "reason": "The requested resource could not be deployed because you are out of available quota.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.user.TermsNotAcceptedYetException",
    "id": 41,
    "reason": "Terms not accepted yet.",
    "type": "USER"
  },
  {
    "exception": "com.redhat.service.smartevents.infra.exceptions.definitions.platform.AMSFailException",
    "id": 42,
    "reason": "An error with AMS occurred.",
    "type": "PLATFORM"
  }
]